"use client";

import { useState } from "react";
import { Bookmark, MessageSquare, Copy, RefreshCw, CheckCircle, AlertCircle } from "lucide-react";
import type { Opportunity } from "@/types";

// ── Copy Outreach Button (inline) ─────────────────────────

interface CopyOutreachButtonProps {
  text: string;
}

export function CopyOutreachButton({ text }: CopyOutreachButtonProps) {
  const [copied, setCopied] = useState(false);

  const copy = () => {
    navigator.clipboard.writeText(text).catch(() => {});
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <button
      id="copy-outreach-btn"
      className="btn btn-secondary btn-sm"
      onClick={copy}
    >
      {copied ? (
        <>
          <CheckCircle size={13} color="#10b981" />
          Copied!
        </>
      ) : (
        <>
          <Copy size={13} />
          Copy
        </>
      )}
    </button>
  );
}

// ── Live Outreach Generator ───────────────────────────────

interface OpportunityActionsProps {
  outreachMessage: string;
  opportunity: Opportunity;
}

export function OpportunityActions({
  outreachMessage,
  opportunity,
}: OpportunityActionsProps) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [liveOutreach, setLiveOutreach] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const currentMessage = liveOutreach ?? outreachMessage;

  const copyMessage = () => {
    navigator.clipboard.writeText(currentMessage).catch(() => {});
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const regenerate = async () => {
    setIsGenerating(true);
    setError(null);

    try {
      const res = await fetch("/api/outreach", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ opportunity }),
      });

      const data = await res.json();

      if (!res.ok) {
        setError(data.error ?? "Failed to generate outreach. Please try again.");
        return;
      }

      setLiveOutreach(data.body as string);
    } catch {
      setError("Network error. Please check your connection.");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: "0.5rem" }}>
      {/* Error message */}
      {error && (
        <div
          style={{
            display: "flex",
            alignItems: "flex-start",
            gap: "0.5rem",
            padding: "0.625rem 0.75rem",
            background: "rgba(239,68,68,0.08)",
            border: "1px solid rgba(239,68,68,0.2)",
            borderRadius: "0.375rem",
          }}
        >
          <AlertCircle size={13} color="#f87171" style={{ flexShrink: 0, marginTop: 1 }} />
          <p style={{ fontSize: "0.75rem", color: "#fca5a5", margin: 0, lineHeight: 1.5 }}>
            {error}
          </p>
        </div>
      )}

      {/* Live indicator */}
      {liveOutreach && (
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: "0.375rem",
            fontSize: "0.6875rem",
            color: "#10b981",
            fontWeight: 500,
          }}
        >
          <div
            style={{
              width: 6,
              height: 6,
              borderRadius: "50%",
              background: "#10b981",
              boxShadow: "0 0 6px rgba(16,185,129,0.6)",
            }}
          />
          Live — generated by Gemini AI
        </div>
      )}

      <button
        id="detail-bookmark-btn"
        className="btn btn-secondary"
        style={{ width: "100%" }}
      >
        <Bookmark size={14} />
        Bookmark Opportunity
      </button>

      <button
        id="detail-outreach-btn"
        className="btn btn-primary"
        style={{ width: "100%" }}
        onClick={copyMessage}
      >
        {copied ? (
          <>
            <CheckCircle size={14} />
            Copied to Clipboard!
          </>
        ) : (
          <>
            <MessageSquare size={14} />
            Copy Outreach Message
          </>
        )}
      </button>

      <button
        id="detail-regenerate-btn"
        className="btn btn-ghost"
        style={{ width: "100%", fontSize: "0.8125rem" }}
        onClick={regenerate}
        disabled={isGenerating}
      >
        {isGenerating ? (
          <>
            <span
              style={{
                width: 13,
                height: 13,
                border: "2px solid rgba(255,255,255,0.2)",
                borderTop: "2px solid var(--text-muted)",
                borderRadius: "50%",
                animation: "spin 0.8s linear infinite",
                display: "inline-block",
              }}
            />
            Generating with Gemini…
          </>
        ) : (
          <>
            <RefreshCw size={13} />
            {liveOutreach ? "Regenerate" : "Generate with Gemini AI"}
          </>
        )}
      </button>

      <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
    </div>
  );
}
