// ============================================================
// AI Provider Abstraction Layer
// ============================================================
// This module defines the contract for all AI providers.
// Connect Gemini, Groq, or OpenAI by implementing AIProvider.
// Never put API keys here — use environment variables only.
// ============================================================

import type {
  IntentAnalysis,
  Opportunity,
  ServiceCategory,
  OutreachDraft,
} from "@/types";

// ----------------------------------------------------------
// AI Provider Interface
// ----------------------------------------------------------

export interface AIProvider {
  name: string;
  isAvailable(): boolean;

  /**
   * Analyze raw content and extract intent signals.
   */
  analyzeIntent(content: string, context?: string): Promise<IntentAnalysis>;

  /**
   * Match content against OBYON service categories.
   */
  matchServices(content: string): Promise<ServiceCategory[]>;

  /**
   * Generate a personalized outreach message draft.
   */
  generateOutreach(opportunity: Opportunity): Promise<OutreachDraft>;
}

// ----------------------------------------------------------
// AI Provider Configuration
// ----------------------------------------------------------

export interface AIProviderConfig {
  provider: "gemini" | "groq" | "openai" | "mock";
  apiKey: string; // Loaded from env — never hardcoded
  model?: string;
  maxTokens?: number;
  temperature?: number;
}

// ----------------------------------------------------------
// Mock Provider (Phase 1 — returns pre-baked analysis)
// ----------------------------------------------------------

export class MockAIProvider implements AIProvider {
  name = "mock";

  isAvailable(): boolean {
    return true;
  }

  async analyzeIntent(content: string): Promise<IntentAnalysis> {
    // TODO Phase 2: Replace with real AI call
    return {
      opportunityId: "",
      provider: "mock",
      analyzedAt: new Date().toISOString(),
      detectedNeed: "AI/automation solution",
      detectedProblem: "Manual or repetitive process causing inefficiency",
      detectedRequirement: "Custom automated solution",
      matchedServices: ["ai_automation"],
      primaryService: "ai_automation",
      intentScore: 70,
      urgencyScore: 65,
      confidenceScore: 75,
      intentStrength: "implicit",
      urgency: "medium",
      budgetSignal: "no_signal",
      reasoning: "Mock analysis — connect AI provider for real analysis",
      suggestedOutreach: "Personalized outreach will be generated by AI provider",
      tags: ["mock"],
      rawResponse: null,
    };
  }

  async matchServices(content: string): Promise<ServiceCategory[]> {
    // TODO Phase 2: Replace with real AI call
    void content;
    return ["ai_automation"];
  }

  async generateOutreach(opportunity: Opportunity): Promise<OutreachDraft> {
    // TODO Phase 2: Replace with real AI call
    return {
      id: `draft-${Date.now()}`,
      opportunityId: opportunity.id,
      platform: opportunity.sourceName,
      subject: null,
      body: opportunity.suggestedOutreach,
      tone: "professional",
      generatedAt: new Date().toISOString(),
      isApproved: false,
    };
  }
}

// ----------------------------------------------------------
// Gemini Provider Stub
// ----------------------------------------------------------

export class GeminiProvider implements AIProvider {
  name = "gemini";
  private apiKey: string;

  constructor() {
    // Never hardcode — load from environment
    this.apiKey = process.env.GEMINI_API_KEY ?? "";
  }

  isAvailable(): boolean {
    return this.apiKey.length > 0;
  }

  async analyzeIntent(_content: string): Promise<IntentAnalysis> {
    if (!this.isAvailable()) {
      throw new Error("Gemini API key not configured. Set GEMINI_API_KEY in .env.local");
    }
    // TODO Phase 2: Implement Gemini API call
    throw new Error("Gemini provider not yet implemented — coming in Phase 2");
  }

  async matchServices(_content: string): Promise<ServiceCategory[]> {
    // TODO Phase 2: Implement Gemini API call
    throw new Error("Gemini provider not yet implemented — coming in Phase 2");
  }

  async generateOutreach(_opportunity: Opportunity): Promise<OutreachDraft> {
    // TODO Phase 2: Implement Gemini API call
    throw new Error("Gemini provider not yet implemented — coming in Phase 2");
  }
}

// ----------------------------------------------------------
// Groq Provider Stub
// ----------------------------------------------------------

export class GroqProvider implements AIProvider {
  name = "groq";
  private apiKey: string;

  constructor() {
    this.apiKey = process.env.GROQ_API_KEY ?? "";
  }

  isAvailable(): boolean {
    return this.apiKey.length > 0;
  }

  async analyzeIntent(_content: string): Promise<IntentAnalysis> {
    if (!this.isAvailable()) {
      throw new Error("Groq API key not configured. Set GROQ_API_KEY in .env.local");
    }
    // TODO Phase 2: Implement Groq API call
    throw new Error("Groq provider not yet implemented — coming in Phase 2");
  }

  async matchServices(_content: string): Promise<ServiceCategory[]> {
    // TODO Phase 2: Implement Groq API call
    throw new Error("Groq provider not yet implemented — coming in Phase 2");
  }

  async generateOutreach(_opportunity: Opportunity): Promise<OutreachDraft> {
    // TODO Phase 2: Implement Groq API call
    throw new Error("Groq provider not yet implemented — coming in Phase 2");
  }
}

// ----------------------------------------------------------
// Provider Factory
// ----------------------------------------------------------

export function createAIProvider(config?: Partial<AIProviderConfig>): AIProvider {
  const provider = config?.provider ?? process.env.AI_PROVIDER ?? "mock";

  switch (provider) {
    case "gemini":
      return new GeminiProvider();
    case "groq":
      return new GroqProvider();
    case "mock":
    default:
      return new MockAIProvider();
  }
}

// Default export — auto-selects based on env
export const aiProvider = createAIProvider();
